### ISSUE TITLE
Look into doing Attendance Tracking in Rink Portal

### ISSUE THREAD

**Issue by dsilvers** [MadisonRollerDerby/rink#47]
Watching Audi type attendance into that spreadsheet is hilarious. There's gotta be a better way....

**Comment by alexhanna** [comment]
What could be some intuitive alternatives to this?

**Comment by dsilvers** [comment]
Move the attendance tracking to the rink portal:

- Generate a PDF of the current attendance sheet for printing. Current Google doc is finicky and problematic for trying to fit into a single double sided sheet.
- Allow for individual attendance reporting in the rink dashboard
- Maybe even historical stats for people or for the league to do future attendance projections/growth/analytics. (ex: summer expects XX% of people to sign up typically, end of session drop-off for attendance, days of week /time of day practice times working better than others)
